INSERT IGNORE INTO config (component, setting, value, type) values ('plugin_csmodule_mapping', 'isconnectedquery', 'N', 'string');
INSERT IGNORE INTO config (component, setting, value, type) values ('plugin_csmodule_mapping', 'maxrows', 1, 'integer');
INSERT IGNORE INTO config (component, setting, value, type) values ('plugin_csmodule_mapping', 'prompt_uniquepromptname', 'promptname', 'string');
INSERT IGNORE INTO config (component, setting, value, type) values ('plugin_csmodule_mapping', 'filterfields', 'filterfields', 'string');
INSERT IGNORE INTO config (component, setting, value, type) values ('plugin_csmodule_mapping', 'url', 'https://www.example.com', 'url');
INSERT IGNORE INTO config (component, setting, value, type) values ('plugin_csmodule_mapping', 'username', 'username', 'string');
INSERT IGNORE INTO config (component, setting, value, type) values ('plugin_csmodule_mapping', 'password', 'password', 'password');
INSERT IGNORE INTO config (component, setting, value, type) values ('plugin_csmodule_mapping', 'timeout', 10, 'integer');
INSERT IGNORE INTO config (component, setting, value, type) values ('plugin_csmodule_mapping', 'ssl_verify', 1, 'boolean');